server:
  port: 8080

spring:
  application:
    name: base-sso
  datasource:
    url: jdbc:postgresql://localhost:5432/base-sso
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    url: jdbc:postgresql://localhost:5432/base-sso
    user: root
    password: admin123
    baseline-on-migrate: true
